services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: password
    restart: always
    networks:
      - my-moodle4

  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8060:80"
    depends_on:
      - db
    volumes:
      - ./moodledata:/var/www/moodledata
      - ./moodle:/var/www/html
    restart: always
    environment:
      MOODLE_DB_HOST: db
      MOODLE_DB_PORT: 3306
      MOODLE_DB_NAME: moodle
      MOODLE_DB_USER: moodle
      MOODLE_DB_PASSWORD: password
      MOODLE_WWW_ROOT: http://localhost:8060
      MOODLE_DATA_ROOT: /var/www/moodledata
    networks:
      - my-moodle4

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8061:80"
    environment:
      PMA_HOST: db
    networks:
      - my-moodle4

networks:
  my-moodle4: null

volumes:
  db_data:
    driver: local
