services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      - my-moodle4

  moodle:
    build:
      context: .
      args:
        - MOODLE_BRANCH
        - MOODLE_RELEASE
        - MOODLE_SHA256
        - MOODLE_DB_HOST
        - MOODLE_DB_PORT
        - MOODLE_DB_NAME
        - MOODLE_DB_USER
        - MOODLE_DB_PASSWORD
        - MOODLE_WWW_ROOT
        - MOODLE_DATA_ROOT
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
      dockerfile: Dockerfile
    ports:
      - "${MOODLE_PORT}:80"
    depends_on:
      - db
    volumes:
      - ./moodledata:/var/www/moodledata
      - ./moodle:/var/www/html
    restart: always
    environment:
      MOODLE_DB_HOST: ${MOODLE_DB_HOST}
      MOODLE_DB_PORT: ${MOODLE_DB_PORT}
      MOODLE_DB_NAME: ${MOODLE_DB_NAME}
      MOODLE_DB_USER: ${MOODLE_DB_USER}
      MOODLE_DB_PASSWORD: ${MOODLE_DB_PASSWORD}
      MOODLE_WWW_ROOT: ${MOODLE_WWW_ROOT}
      MOODLE_DATA_ROOT: ${MOODLE_DATA_ROOT}
    networks:
      - my-moodle4

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
    networks:
      - my-moodle4

networks:
  my-moodle4: null

volumes:
  db_data:
    driver: local
